name: fastscape-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray-simlab=0.5.0
  - xarray
  - ipython
  - nbconvert
  - sphinx
  - pandoc
  - fastscapelib-f2py=2.8.3
  - numba
  - sphinx_rtd_theme
  - pip
  - pip:
      - -e ..
