name: fastscape-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - xarray-simlab=0.4.1
  - xarray=0.13.0
  - ipython=7.8.0
  - nbconvert=5.6.0
  - sphinx=1.8.5
  - pandoc=2.7.3
  - fastscapelib-f2py=2.8.2
  - numba=0.45.1
  - sphinx_rtd_theme
